name: main
on:
  - push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.2
    - run: make build
    - run: make fmt/check
    - run: make vet
    - run: make test
